### ISSUE TITLE
Error running on Ubuntu 14.04

### ISSUE THREAD

**Issue by jakub-g** [jakub-g/x-default-browser#1]
From https://github.com/node-inspector/node-inspector/issues/567

```
/usr/lib/node_modules/node-inspector/node_modules/biased-opener/index.js:97
var goodEnough = isDefaultBrowserGoodEnough(browserInfo.commonName, pr
^
TypeError: Cannot read property 'commonName' of undefined
at /usr/lib/node_modules/node-inspector/node_modules/biased-opener/index.js:97:64
at /usr/lib/node_modules/node-inspector/node_modules/biased-opener/node_modules/x-default-browser/lib/detect-linux.js:9:13
```

**Comment by jakub-g** [comment]
@roysG can you please do the following to help me debug this issue? I could not reproduce it on my Ubuntu 14.04 VM (I installed Chrome from http://www.google.com/chrome/).

```
mkdir temp_dir
cd temp_dir
npm install x-default-browser
touch test.js
gedit test.js  # put contents as below
nodejs test.js
```

`test.js`:

```
var defaultBrowser = require('x-default-browser');
defaultBrowser(function (err, res) {
  console.log(err);
  console.dir(res);
});
```

Likely it will log an error in the first line, I want to know what kind of error it is
